/* It had generated by DirectStruct v1.9.1 */
#include "IDL_testable.dsc.h"

static int		_DSC_errline = 0 ;

int DSCINIT_testable( testable *pst )
{
	int	index[10] = { 0 } ; index[0]++; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(testable) );
	return 0;
}
int DSCGetErrorLine_testable()
{
	return _DSC_errline;
}

