/* It had generated by DirectStruct v1.5.0 */
#include "IDL_testable.dsc.h"

int DSCINIT_testable( testable *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(testable) );
	return 0;
}
