/* It had generated by DirectStruct v1.12.2 */
#include "IDL_CommHead.dsc.h"

static int		_DSC_errline = 0 ;

int DSCINIT_CommHead( CommHead *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(CommHead) );
	return 0;
}

int DSCNETORDER_CommHead( CommHead *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	pst->length=(int)htonl((unsigned int)(pst->length));
	return 0;
}

int DSCHOSTORDER_CommHead( CommHead *pst )
{
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	pst->length=(int)ntohl((unsigned int)(pst->length));
	return 0;
}

int DSCSERIALIZE_COMPACT_CommHead( CommHead *pst , char *buf , int *p_len )
{
	char	*ptr = buf ;
	int	len = 0 ;
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	
	/* length */
	{ int i; i=(int)htonl((unsigned int)(pst->length)); memcpy( ptr , (char*)&i , 4 ); }
	len+=4; ptr+=4;
	
	if( p_len ) (*p_len) = len ;
	
	return 0;
}

int DSCDESERIALIZE_COMPACT_CommHead( char *buf , int *p_len , CommHead *pst )
{
	char	*ptr = buf ;
	int	len = 0 ;
	int	index[10] = { 0 } ;
	index[0]++; index[0] = 0 ;
	
	/* length */
	memcpy( (char*)&(pst->length) , ptr , 4 ); pst->length=(int)htonl((unsigned int)(pst->length));
	len+=4; ptr+=4;
	
	if( p_len ) (*p_len) = len ;
	
	return 0;
}
int DSCGetErrorLine_CommHead()
{
	return _DSC_errline;
}

