/* It had generated by DirectStruct v1.13.0 */
#ifndef _H_OrgCustBaseInfoQueryRequest_
#define _H_OrgCustBaseInfoQueryRequest_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if ( defined __unix ) || ( defined __linux__ )
#ifndef _WINDLL_FUNC
#define _WINDLL_FUNC
#endif
#elif ( defined _WIN32 )
#ifndef _WINDLL_FUNC
#define _WINDLL_FUNC		_declspec(dllexport)
#endif
#endif

#ifndef DSCTRUE
#define DSCTRUE	(unsigned char)'t'
#endif
#ifndef DSCFALSE
#define DSCFALSE	(unsigned char)'f'
#endif
#ifndef DSCNULL
#define DSCNULL	(unsigned char)127
#endif

#if ( defined __unix ) | ( defined __linux__ )
#include <arpa/inet.h>
#define SNPRINTF		snprintf
#elif ( defined _WIN32 )
#define SNPRINTF		_snprintf
#include "winsock.h"
#endif

#if ( defined __unix ) | ( defined __linux__ )
#ifndef longlong
#define longlong	long long
#define ulonglong	unsigned long long
#ifndef LL
#define LL(_ll_)	_ll_##LL
#define ULL(_ll_)	_ll_##ULL
#endif
#define LONGLONG_FORMAT_SPEC	"%lld"
#define ATOLL	atoll
#endif
#if ( defined _AIX )
#define __BIG_ENDIAN	BIG_ENDIAN
#define __LITTLE_ENDIAN	LITTLE_ENDIAN
#define __BYTE_ORDER	BYTE_ORDER
#endif
#elif ( defined _WIN32 )
#ifndef longlong
#define longlong	__int64
#define ulonglong	unsigned __int64
#ifndef LL
#define LL(_ll_)	_ll_
#define ULL(_ll_)	_ll_
#endif
#define LONGLONG_FORMAT_SPEC	"%I64"
#define ATOLL	_atoi64
#define __BIG_ENDIAN	4321
#define __LITTLE_ENDIAN	1234
#define __BYTE_ORDER	__LITTLE_ENDIAN
#endif
#endif

#ifndef NATOC
#define NATOC(_base_,_len_,_result_)	{_result_=_base_[0];}
#endif
#ifndef NATOI1
#define NATOI1(_base_,_len_,_result_)	{char buf[3+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,3);_result_=(char)atoi(buf);}
#endif
#ifndef NATOS
#define NATOS(_base_,_len_,_result_)	{char buf[5+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,5);_result_=(short)atol(buf);}
#endif
#ifndef NATOI
#define NATOI(_base_,_len_,_result_)	{char buf[10+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,10);_result_=atoi(buf);}
#endif
#ifndef NATOLL
#define NATOLL(_base_,_len_,_result_)	{char buf[20+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,20);_result_=ATOLL(buf);}
#endif
#ifndef NATOF
#define NATOF(_base_,_len_,_result_)	{char buf[20+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,20);_result_=(float)atof(buf);}
#endif
#ifndef NATOLF
#define NATOLF(_base_,_len_,_result_)	{char buf[60+1];memset(buf,0x00,sizeof(buf));strncpy(buf,_base_,60);_result_=atof(buf);}
#endif
#ifndef NATOB
#define NATOB(_base_,_len_,_result_)	{if(memcmp(_base_,"true",4)==0)_result_=DSCTRUE;else _result_=DSCFALSE;}
#endif

typedef struct
{
	struct
	{
		struct
		{
			char	TransactionRef[ 20 + 1 ] ;
			char	ProjectCode[ 20 + 1 ] ;
			char	BranchNo[ 10 + 1 ] ;
			char	SourceChannel[ 4 + 1 ] ;
			char	Language[ 4 + 1 ] ;
			char	VersionNo[ 10 + 1 ] ;
			char	TerminalNo[ 16 + 1 ] ;
			char	SystemType[ 2 + 1 ] ;
			char	OperatorId[ 12 + 1 ] ;
			char	SessionToken[ 128 + 1 ] ;
			char	SenderNode[ 10 + 1 ] ;
			char	SenderServer[ 10 + 1 ] ;
			char	SenderJournalNo[ 20 + 1 ] ;
			char	SenderDate[ 10 + 1 ] ;
			char	SenderTime[ 10 + 1 ] ;
			char	TransferNode[ 10 + 1 ] ;
			char	TransferServer[ 10 + 1 ] ;
			char	TransferJournalNo[ 20 + 1 ] ;
			char	TransferDate[ 10 + 1 ] ;
			char	TransferTime[ 10 + 1 ] ;
		} SysReqHeader ;
		struct
		{
			char	MessageType[ 4 + 1 ] ;
			char	TransactionCode[ 10 + 1 ] ;
			int	SecondStamp ;
			char	AuthorOperatorId[ 12 + 1 ] ;
			char	AuthorFingerprint[ 512 + 1 ] ;
			char	AuthorPassword[ 48 + 1 ] ;
			int	RelatedCycleNo ;
			char	RelatedAccDate[ 10 + 1 ] ;
			char	CheckOperatorId[ 12 + 1 ] ;
			char	Reserve[ 256 + 1 ] ;
		} TxnReqHeader ;
	} RequestHeader ;
	struct
	{
		struct
		{
			char	cust_recog[ 30 + 1 ] ;
			char	customer_no[ 30 + 1 ] ;
			char	customer_name[ 120 + 1 ] ;
			char	id_type[ 30 + 1 ] ;
			char	id_no[ 60 + 1 ] ;
		} CustIdentZone ;
	} RequestBody ;
} OrgCustBaseInfoQueryRequest ;

_WINDLL_FUNC int DSCINIT_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst );

_WINDLL_FUNC int DSCSERIALIZE_XML_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst , char *encoding , char *buf , int *p_len );
_WINDLL_FUNC int DSCSERIALIZE_XML_DUP_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst , char *encoding , char **pp_base , int *p_buf_size , int *p_len );
_WINDLL_FUNC int DSCSERIALIZE_XML_DUP_OrgCustBaseInfoQueryRequest_V( void *pst , char *encoding , char **pp_base , int *p_buf_size , int *p_len );
_WINDLL_FUNC int DSCDESERIALIZE_XML_OrgCustBaseInfoQueryRequest( char *encoding , char *buf , int *p_len , OrgCustBaseInfoQueryRequest *pst );
_WINDLL_FUNC int DSCDESERIALIZE_XML_OrgCustBaseInfoQueryRequest_V( char *encoding , char *buf , int *p_len , void *pst );

_WINDLL_FUNC int DSCSERIALIZE_XML_COMPACT_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst , char *encoding , char *buf , int *p_len );
_WINDLL_FUNC int DSCSERIALIZE_XML_COMPACT_DUP_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst , char *encoding , char **pp_base , int *p_buf_size , int *p_len );
_WINDLL_FUNC int DSCSERIALIZE_XML_COMPACT_DUP_OrgCustBaseInfoQueryRequest_V( void *pst , char *encoding , char **pp_base , int *p_buf_size , int *p_len );
_WINDLL_FUNC int DSCDESERIALIZE_XML_COMPACT_OrgCustBaseInfoQueryRequest( char *encoding , char *buf , int *p_len , OrgCustBaseInfoQueryRequest *pst );
_WINDLL_FUNC int DSCDESERIALIZE_XML_COMPACT_OrgCustBaseInfoQueryRequest_V( char *encoding , char *buf , int *p_len , void *pst );

int DSCGetErrorLine_OrgCustBaseInfoQueryRequest();

#endif
