/* It had generated by DirectStruct v1.13.0 */
#include "testppp.dsc.h"

#ifndef FUNCNAME_DSCLOG_OrgCustBaseInfoQueryRequest
#define FUNCNAME_DSCLOG_OrgCustBaseInfoQueryRequest	DSCLOG_OrgCustBaseInfoQueryRequest
#endif

#ifndef PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest
#define PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest	printf( 
#endif

#ifndef NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest
#define NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest	"\n"
#endif

int FUNCNAME_DSCLOG_OrgCustBaseInfoQueryRequest( OrgCustBaseInfoQueryRequest *pst )
{
	int	index[10] = { 0 } ; index[0]++; index[0] = 0 ;
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransactionRef[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransactionRef );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.ProjectCode[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.ProjectCode );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.BranchNo[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.BranchNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SourceChannel[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SourceChannel );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.Language[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.Language );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.VersionNo[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.VersionNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TerminalNo[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TerminalNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SystemType[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SystemType );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.OperatorId[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.OperatorId );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SessionToken[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SessionToken );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SenderNode[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SenderNode );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SenderServer[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SenderServer );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SenderJournalNo[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SenderJournalNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SenderDate[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SenderDate );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.SenderTime[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.SenderTime );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransferNode[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransferNode );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransferServer[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransferServer );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransferJournalNo[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransferJournalNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransferDate[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransferDate );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.SysReqHeader.TransferTime[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.SysReqHeader.TransferTime );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.MessageType[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.MessageType );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.TransactionCode[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.TransactionCode );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.SecondStamp[%d]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.SecondStamp );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.AuthorOperatorId[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.AuthorOperatorId );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.AuthorFingerprint[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.AuthorFingerprint );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.AuthorPassword[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.AuthorPassword );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.RelatedCycleNo[%d]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.RelatedCycleNo );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.RelatedAccDate[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.RelatedAccDate );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.CheckOperatorId[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.CheckOperatorId );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestHeader.TxnReqHeader.Reserve[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestHeader.TxnReqHeader.Reserve );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestBody.CustIdentZone.cust_recog[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestBody.CustIdentZone.cust_recog );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestBody.CustIdentZone.customer_no[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestBody.CustIdentZone.customer_no );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestBody.CustIdentZone.customer_name[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestBody.CustIdentZone.customer_name );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestBody.CustIdentZone.id_type[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestBody.CustIdentZone.id_type );
			PREFIX_DSCLOG_OrgCustBaseInfoQueryRequest "OrgCustBaseInfoQueryRequest.RequestBody.CustIdentZone.id_no[%s]" NEWLINE_DSCLOG_OrgCustBaseInfoQueryRequest , pst->RequestBody.CustIdentZone.id_no );
	return 0;
}
