/* It had generated by DirectStruct v1.3.0 */
#include "IDL_userinfo.dsc.h"

#ifndef FUNCNAME_DSCLOG_userinfo
#define FUNCNAME_DSCLOG_userinfo	DSCLOG_userinfo
#endif

#ifndef PREFIX_DSCLOG_userinfo
#define PREFIX_DSCLOG_userinfo	printf( 
#endif

#ifndef NEWLINE_DSCLOG_userinfo
#define NEWLINE_DSCLOG_userinfo	"\n"
#endif

int FUNCNAME_DSCLOG_userinfo( userinfo *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	PREFIX_DSCLOG_userinfo "userinfo.user_id[%d]" NEWLINE_DSCLOG_userinfo , pst->user_id );
	PREFIX_DSCLOG_userinfo "userinfo.user_name[%s]" NEWLINE_DSCLOG_userinfo , pst->user_name );
	PREFIX_DSCLOG_userinfo "userinfo.email[%s]" NEWLINE_DSCLOG_userinfo , pst->email );
	return 0;
}
