/* It had generated by DirectStruct v1.1.0 */
#ifndef _H_userinfo_ESQL_
#define _H_userinfo_ESQL_

#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>

#include "IDL_userinfo.dsc.h"

#ifndef SQLCODE
#define SQLCODE		sqlca.sqlcode
#define SQLSTATE	sqlca.sqlstate
#endif

EXEC SQL BEGIN DECLARE SECTION ;
	extern int userinfo_user_id ;	extern short userinfo_user_id_id ;
	extern char userinfo_user_name[ 16 + 1 ] ;	extern short userinfo_user_name_id ;
	extern char userinfo_email[ 128 + 1 ] ;	extern short userinfo_email_id ;
EXEC SQL END DECLARE SECTION ;

#define	TFLIST_userinfo \
	user_id , \
	user_name , \
	email

#define	DBVLIST_userinfo \
	:userinfo_user_id , \
	:userinfo_user_name , \
	:userinfo_email

#define	DBVLLIST_userinfo \
	:userinfo_user_id :userinfo_user_id_id , \
	:userinfo_user_name :userinfo_user_name_id , \
	:userinfo_email :userinfo_email_id

void DSCINITV_userinfo();
void DSCVTOS_userinfo( userinfo *pst );
void DSCSTOV_userinfo( userinfo *pst );
void DSCTRIM_userinfo( userinfo *pst );

#endif
