/* It had generated by DirectStruct v1.1.0 */
#include "IDL_userinfo.dsc.h"

int DSCINIT_userinfo( userinfo *pst )
{
	int	index[10] = { 0 } ; index[0] = 0 ;
	memset( pst , 0x00 , sizeof(userinfo) );
	return 0;
}

#include "fasterxml.h"

int DSCSERIALIZE_XML_userinfo( userinfo *pst , char *encoding , char *buf , int *p_len )
{
	int	remain_len ;
	int	len ;
	char	tabs[10+1] ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	remain_len = (*p_len) - 1 ;
	memset( tabs , '\t' , 10 );
	len=SNPRINTF(buf,remain_len,"<?xml version=\"1.0\" encoding=\"%s\"?>\n",encoding); if( len <= 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"<userinfo>\n"); if( len <= 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"	<user_id>"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"%d",pst->user_id); XMLESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
		len=SNPRINTF(buf,remain_len,"</user_id>\n"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"	<user_name>"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"%s",pst->user_name); XMLESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
		len=SNPRINTF(buf,remain_len,"</user_name>\n"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"	<email>"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
		len=SNPRINTF(buf,remain_len,"%s",pst->email); XMLESCAPE_EXPAND(buf,len,remain_len); if( len < 0 ) return -1;
		len=SNPRINTF(buf,remain_len,"</email>\n"); if( len < 0 ) return -1; buf+=len; remain_len-=len;
	len=SNPRINTF(buf,remain_len,"</userinfo>\n"); if( len <= 0 ) return -1; buf+=len; remain_len-=len;
	
	if( p_len ) (*p_len) = (*p_len)-1 - remain_len ;
	
	return 0;
}

funcCallbackOnXmlNode CallbackOnXmlNode_userinfo ;
int CallbackOnXmlNode_userinfo( int type , char *xpath , int xpath_len , int xpath_size , char *nodename , int nodename_len , char *properties , int properties_len , char *content , int content_len , void *p )
{
	userinfo	*pst = (userinfo*)p ;
	int	index[10] = { 0 } ; index[0] = 0 ;
	
	if( type & FASTERXML_NODE_BRANCH )
	{
		if( type & FASTERXML_NODE_ENTER )
		{
		}
		else if( type & FASTERXML_NODE_LEAVE )
		{
		}
	}
	else if( type & FASTERXML_NODE_LEAF )
	{
		/* user_id */
		if( strncmp( xpath , "/userinfo/user_id" , xpath_len ) == 0 )
		{NATOI(content,content_len,pst->user_id);}
		/* user_name */
		if( strncmp( xpath , "/userinfo/user_name" , xpath_len ) == 0 )
		{XMLUNESCAPE_FOLD(content,content_len,pst->user_name);
		{if( content_len > sizeof(pst->user_name)-1 ) return -7;}}
		/* email */
		if( strncmp( xpath , "/userinfo/email" , xpath_len ) == 0 )
		{XMLUNESCAPE_FOLD(content,content_len,pst->email);
		{if( content_len > sizeof(pst->email)-1 ) return -7;}}
	}
	
	return 0;
}

int DSCDESERIALIZE_XML_userinfo( char *encoding , char *buf , int *p_len , userinfo *pst )
{
	char	xpath[ 1024 + 1 ] ;
	int	nret = 0 ;
	memset( xpath , 0x00 , sizeof(xpath) );
	nret = TravelXmlBuffer( buf , xpath , sizeof(xpath) , & CallbackOnXmlNode_userinfo , (void*)pst ) ;
	if( nret && nret != FASTERXML_INFO_END_OF_BUFFER )
		return nret;
	
	return 0;
}
