/* It had generated by DirectStruct v1.1.0 */

#include "IDL_userinfo.dsc.ESQL.eh"

EXEC SQL BEGIN DECLARE SECTION ;
	int userinfo_user_id ;	short userinfo_user_id_id ;
	char userinfo_user_name[ 16 + 1 ] ;	short userinfo_user_name_id ;
	char userinfo_email[ 128 + 1 ] ;	short userinfo_email_id ;
EXEC SQL END DECLARE SECTION ;

void DSCINITV_userinfo()
{
	userinfo_user_id = 0 ;
	userinfo_user_id_id = 0 ;
	memset( userinfo_user_name , 0x00 , sizeof(userinfo_user_name) );
	userinfo_user_name_id = 0 ;
	memset( userinfo_email , 0x00 , sizeof(userinfo_email) );
	userinfo_email_id = 0 ;
	return;
}

void DSCVTOS_userinfo( userinfo *pst )
{
	pst->user_id = userinfo_user_id ;
	strcpy( pst->user_name , userinfo_user_name );
	strcpy( pst->email , userinfo_email );
	return;
}

void DSCSTOV_userinfo( userinfo *pst )
{
	userinfo_user_id = pst->user_id ;
	strcpy( userinfo_user_name , pst->user_name );
	strcpy( userinfo_email , pst->email );
	return;
}

#ifndef TRIM
#define TRIM(_str_) {char *p=(_str_)+strlen(_str_)-1; for(;((*p)==' ')&&(p>=(_str_));p--){(*p)='\0';}}
#endif

void DSCTRIM_userinfo( userinfo *pst )
{
	TRIM( pst->user_name )
	TRIM( pst->email )
	return;
}
