# 此文件由makelocal.sh自动生成
# 此文件由makeobj.sh自动生成
############################################################
# 项目名 : 
# 模块名 : 
# 备  注 : 
############################################################

###### 源文件配置区
# 编译宏
AR		=	ar
AFLAGS		=	rv
SOFLAGS		=	-G -bnoentry
ESOFLAGS	=	-bdynamic -brtl -qcpluscm

# c源代码文件宏及推导规则
CC		=	xlc -q64 -O2 -qlanglvl=ansi -qsrcmsg -qinfo=dcl:eff:ini:par:pro:rea:ret
CC_NOWARN	=	xlc -q64 -O2

c_FILE_o	=	$(c_FILE:.c=.o)
c_FILE2_o	=	$(c_FILE2:.c=.o)
c_FILE3_o	=	$(c_FILE3:.c=.o)
c_FILE4_o	=	$(c_FILE4:.c=.o)
c_FILE5_o	=	$(c_FILE5:.c=.o)
c_FILE_CLEAN	=	$(c_FILE_o) $(c_FILE2_o) $(c_FILE3_o) $(c_FILE4_o) $(c_FILE5_o)

.SUFFIXES:.c
.c.o	:
	$(CC) $(CFLAGS) -c $<

c_FILE		=	\
			IDL_userinfo.dsc.c		\
			test_client.c			\
			test_server.c			\
			test_db2json.c			\

###### 目标文件、安装目录配置区
BIN		=	test_client			\
			test_server			\
			test_db2json			\

###### 编译选项
CFLAGS		=	-I. \
			-I/root/local/postgresql/include\
			-I/usr/include/fasterxml	\
			-I/usr/include/fasterjson	\

###### 链接选项
LFLAGS		=	-L. \
			-L/root/local/postgresql/lib	\
			-lecpg				\
			-L/usr/lib			\
			-lfasterxml			\
			-lfasterjson			\

###### 额外宏定义区
CLEAN_ADDITION	=

###### 加载mktpl模板库
# 最终目标列表
all	:	$(OBJ) $(OBJ2) $(LIB) $(LIB2) $(SQL) $(NOCLEAN_OBJ) $(NOINST_OBJ) $(BIN) $(BIN2)

# 文件系统宏
CD		=	cd
RM		=	rm -f
CP		=	cp -f
MV		=	mv -f
MKDIR		=	mkdir -p

# 预定义源文件清理删除关联宏
_FILE_CLEAN	=	$(c_FILE_CLEAN) $(cpp_FILE_CLEAN) $(SQC_FILE_CLEAN) $(csm_FILE_CLEAN) $(c_html_FILE_CLEAN) $(cui_FILE_CLEAN) $(dtd_FILE_CLEAN) $(prt_FILE_CLEAN) $(fmd_FILE_CLEAN) $(smd_FILE_CLEAN) $(def_FILE_CLEAN) $(act_FILE_CLEAN)

# 清理删除规则
clean		:
	@for FILE in $(_FILE_CLEAN) $(BIN) $(BIN2) $(LIB) $(LIB2) $(OBJ) $(OBJ2) $(NOINST_OBJ) $(CLEAN_ADDITION) ; do \
		echo $(RM) $$FILE ; \
		$(RM) $$FILE ; \
	done


# 预定义源代码缺省头文件宏
DFTHDER		=	$(csm_FILE_DFTHDER) $(cui_FILE_DFTHDER) $(dtd_FILE_DFTHDER) $(prt_FILE_DFTHDER) $(fmd_FILE_DFTHDER) $(smd_FILE_DFTHDER) $(def_FILE_DFTHDER) $(act_FILE_DFTHDER)

# 提交安装规则
install		:	all

	@if [ -n "$(BIN)" -a -n "$(BININST)" ] ; then \
		if [ ! -d "$(BININST)" ] ; then \
			echo $(MKDIR) $(BININST) ; \
			$(MKDIR) $(BININST) ; \
		fi ; \
		for FILE in `echo $(BIN)` ; do \
			echo $(CP) $$FILE $(BININST)/ ; \
			$(RM) $(BININST)/$$FILE ; \
			$(CP) $$FILE $(BININST)/ ; \
		done \
	fi

	@if [ -n "$(HDER)" -a -n "$(HDERINST)" ] ; then \
		if [ ! -d "$(HDERINST)" ] ; then \
			echo $(MKDIR) $(HDERINST) ; \
			$(MKDIR) $(HDERINST) ; \
		fi ; \
		for FILE in `echo $(HDER)` ; do \
			echo $(CP) $$FILE $(HDERINST)/ ; \
			$(RM) $(HDERINST)/$$FILE ; \
			$(CP) $$FILE $(HDERINST)/ ; \
		done \
	fi

	@if [ -n "$(DFTHDER)" -a -n "$(DFTHDERINST)" ] ; then \
		if [ ! -d "$(DFTHDERINST)" ] ; then \
			echo $(MKDIR) $(DFTHDERINST) ; \
			$(MKDIR) $(DFTHDERINST) ; \
		fi ; \
		for FILE in `echo $(DFTHDER)` ; do \
			echo $(CP) $$FILE $(DFTHDERINST)/ ; \
			$(RM) $(DFTHDERINST)/$$FILE ; \
			$(CP) $$FILE $(DFTHDERINST)/ ; \
		done \
	fi



###### 目标文件依赖关系
test_client	:	IDL_userinfo.dsc.o test_client.o
	$(CC) -o $@ IDL_userinfo.dsc.o test_client.o $(LFLAGS)

ECP	=	ecpg

test_server.o	:	test_server.ec
	$(CC) $(CFLAGS) -E -x c test_server.ec > test_server.ecE
	$(ECP) -h test_server.ecE -o test_server.c
	sed -i 's/NULL/0/g' test_server.c
	$(CC) $(CFLAGS) -c test_server.c

IDL_userinfo.dsc.ESQL.o	:	IDL_userinfo.dsc.ESQL.ec
	$(CC) $(CFLAGS) -E -x c IDL_userinfo.dsc.ESQL.ec > IDL_userinfo.dsc.ESQL.ecE
	$(ECP) -h IDL_userinfo.dsc.ESQL.ecE -o IDL_userinfo.dsc.ESQL.c
	sed -i 's/NULL/0/g' IDL_userinfo.dsc.ESQL.c
	$(CC) $(CFLAGS) -c IDL_userinfo.dsc.ESQL.c

test_server	:	IDL_userinfo.dsc.o IDL_userinfo.dsc.ESQL.o test_server.o
	$(CC) -o $@ IDL_userinfo.dsc.o IDL_userinfo.dsc.ESQL.o test_server.o $(LFLAGS)

test_db2json.o	:	test_db2json.ec
	$(CC) $(CFLAGS) -E -x c test_db2json.ec > test_db2json.ecE
	$(ECP) -h test_db2json.ecE -o test_db2json.c
	sed -i 's/NULL/0/g' test_db2json.c
	$(CC) $(CFLAGS) -c test_db2json.c

test_db2json	:	IDL_userinfo.dsc.o IDL_userinfo.dsc.ESQL.o test_db2json.o
	$(CC) -o $@ IDL_userinfo.dsc.o IDL_userinfo.dsc.ESQL.o test_db2json.o $(LFLAGS)

CLEAN_ADDITION	=	IDL_userinfo.dsc.ESQL.ecE IDL_userinfo.dsc.ESQL.c	\
			test_server.ecE test_server.c				\
			test_db2json.ecE test_db2json.c				\

