#include "dsc.h"

/*
 * dsc - DirectSrtuct compiler
 * author	: calvin
 * email	: calvinwilliams.c@gmail.com
 *
 * Licensed under the LGPL v2.1, see the file LICENSE in base directory.
 */

int GenerateSqlCode_sql_create( struct StructInfo *psi , FILE *fp_dsc_create_sql )
{
	struct FieldInfo	*pfi = NULL ;
	int			flag ;
	
	int			c ;
	
	fprintf( fp_dsc_create_sql , "-- It had generated by DirectStruct v%s\n" , DIRECTSTRUCT_VERSION );
	fprintf( fp_dsc_create_sql , "\n" );
	fprintf( fp_dsc_create_sql , "CREATE TABLE %s\n" , psi->struct_name );
	fprintf( fp_dsc_create_sql , "(\n" );
	for( pfi = psi->field_list ; pfi ; pfi = pfi->next_field )
	{
		flag = 1 ;
		if( STRCMP( pfi->field_type , == , "INT" ) )
		{
			if( pfi->field_len == 1 )
			{
				fprintf( fp_dsc_create_sql , "	%s	SMALLINT" , pfi->field_name );
			}
			else if( pfi->field_len == 2 )
			{
				fprintf( fp_dsc_create_sql , "	%s	SMALLINT" , pfi->field_name );
			}
			else if( pfi->field_len == 4 )
			{
				fprintf( fp_dsc_create_sql , "	%s	INTEGER" , pfi->field_name );
			}
			else if( pfi->field_len == 8 )
			{
				fprintf( fp_dsc_create_sql , "	%s	BIGINT" , pfi->field_name );
			}
			else
			{
				flag = 0 ;
			}
		}
		else if( STRCMP( pfi->field_type , == , "FLOAT" ) )
		{
			if( pfi->field_len == 4 )
			{
				fprintf( fp_dsc_create_sql , "	%s	REAL" , pfi->field_name );
			}
			else if( pfi->field_len == 8 )
			{
				fprintf( fp_dsc_create_sql , "	%s	DOUBLE PRECISION" , pfi->field_name );
			}
			else
			{
				flag = 0 ;
			}
		}
		else if( STRCMP( pfi->field_type , == , "STRING" ) )
		{
			fprintf( fp_dsc_create_sql , "	%s	CHARACTER VARYING(%d)" , pfi->field_name , pfi->field_len );
		}
		else
		{
			flag = 0 ;
		}
		
		if( flag == 1 )
		{
			if( STRCMP( pfi->init_default , != , "" ) )
			{
				if( STRCMP( pfi->field_type , == , "STRING" ) )
					fprintf( fp_dsc_create_sql , "	DEFAULT \"%s\"" , pfi->init_default );
				else
					fprintf( fp_dsc_create_sql , "	DEFAULT %s" , pfi->init_default );
			}
			
			if( pfi->next_field )
			{
				fprintf( fp_dsc_create_sql , " ,\n" );
			}
			else
			{
				fprintf( fp_dsc_create_sql , "\n" );
			}
		}
	}
	fprintf( fp_dsc_create_sql , ") ;\n" );
	
	for( c = 0 ; c < psi->create_sql_count ; c++ )
	{
		fprintf( fp_dsc_create_sql , "\n" );
		fprintf( fp_dsc_create_sql , "%s\n" , psi->create_sql[c] );
	}
	
	return 0;
}

int GenerateSqlCode_sql_drop( struct StructInfo *psi , FILE *fp_dsc_drop_sql )
{
	int			c ;
	
	fprintf( fp_dsc_drop_sql , "-- It had generated by DirectStruct v%s\n" , DIRECTSTRUCT_VERSION );
	
	for( c = 0 ; c < psi->drop_sql_count ; c++ )
	{
		fprintf( fp_dsc_drop_sql , "\n" );
		fprintf( fp_dsc_drop_sql , "%s\n" , psi->drop_sql[c] );
	}
	
	fprintf( fp_dsc_drop_sql , "\n" );
	fprintf( fp_dsc_drop_sql , "DROP TABLE %s ;\n" , psi->struct_name );
	fprintf( fp_dsc_drop_sql , "\n" );
	
	return 0;
}

int GenerateSqlCode( struct CommandParameter *pcp , struct StructInfo *psi , FILE *fp_dsc_create_sql , FILE *fp_dsc_drop_sql )
{
	int		nret = 0 ;
	
	/* Generate *.dsc.create.sql */
	nret = GenerateSqlCode_sql_create( psi->next_struct , fp_dsc_create_sql ) ;
	if( nret )
		return nret;
	
	/* Generate *.dsc.drop.sql */
	nret = GenerateSqlCode_sql_drop( psi->next_struct , fp_dsc_drop_sql ) ;
	if( nret )
		return nret;
	
	return 0;
}

