#include "dsc.h"

/*
 * dsc - DirectSrtuct compiler
 * author	: calvin
 * email	: calvinwilliams.c@gmail.com
 *
 * Licensed under the LGPL v2.1, see the file LICENSE in base directory.
 */

int GenerateSqlCode_sql_create( struct StructInfo *pstruct , FILE *fp_dsc_create_sql )
{
	struct FieldInfo	*pfield = NULL ;
	int			flag ;
	
	int			c ;
	
	fprintf( fp_dsc_create_sql , "-- It had generated by DirectStruct v%s\n" , DIRECTSTRUCT_VERSION );
	fprintf( fp_dsc_create_sql , "\n" );
	fprintf( fp_dsc_create_sql , "CREATE TABLE %s\n" , pstruct->struct_name );
	fprintf( fp_dsc_create_sql , "(\n" );
	for( pfield = pstruct->field_list ; pfield ; pfield = pfield->next_field )
	{
		flag = 1 ;
		if( STRCMP( pfield->field_type , == , "INT" ) )
		{
			if( pfield->field_len == 1 )
			{
				fprintf( fp_dsc_create_sql , "	%s	SMALLINT" , pfield->field_name );
			}
			else if( pfield->field_len == 2 )
			{
				fprintf( fp_dsc_create_sql , "	%s	SMALLINT" , pfield->field_name );
			}
			else if( pfield->field_len == 4 )
			{
				fprintf( fp_dsc_create_sql , "	%s	INTEGER" , pfield->field_name );
			}
			else if( pfield->field_len == 8 )
			{
				fprintf( fp_dsc_create_sql , "	%s	BIGINT" , pfield->field_name );
			}
			else
			{
				flag = 0 ;
			}
		}
		else if( STRCMP( pfield->field_type , == , "FLOAT" ) )
		{
			if( pfield->field_len == 4 )
			{
				fprintf( fp_dsc_create_sql , "	%s	REAL" , pfield->field_name );
			}
			else if( pfield->field_len == 8 )
			{
				fprintf( fp_dsc_create_sql , "	%s	DOUBLE PRECISION" , pfield->field_name );
			}
			else
			{
				flag = 0 ;
			}
		}
		else if( STRCMP( pfield->field_type , == , "STRING" ) )
		{
			fprintf( fp_dsc_create_sql , "	%s	CHARACTER VARYING(%d)" , pfield->field_name , pfield->field_len );
		}
		else
		{
			flag = 0 ;
		}
		
		if( flag == 1 )
		{
			if( STRCMP( pfield->init_default , != , "" ) )
			{
				if( STRCMP( pfield->field_type , == , "STRING" ) )
					fprintf( fp_dsc_create_sql , "	DEFAULT '%s'" , pfield->init_default );
				else
					fprintf( fp_dsc_create_sql , "	DEFAULT %s" , pfield->init_default );
			}
			
			if( pfield->null_or_notnull == DSC_FIELD_NULL )
			{
				fprintf( fp_dsc_create_sql , " NULL" );
			}
			else if( pfield->null_or_notnull == DSC_FIELD_NOTNULL )
			{
				fprintf( fp_dsc_create_sql , " NOT NULL" );
			}
			
			if( pfield->next_field )
			{
				fprintf( fp_dsc_create_sql , " ,\n" );
			}
			else
			{
				fprintf( fp_dsc_create_sql , "\n" );
			}
		}
	}
	fprintf( fp_dsc_create_sql , ") ;\n" );
	
	for( c = 0 ; c < pstruct->create_sql_count ; c++ )
	{
		fprintf( fp_dsc_create_sql , "\n" );
		fprintf( fp_dsc_create_sql , "%s\n" , pstruct->create_sql[c] );
	}
	
	return 0;
}

int GenerateSqlCode_sql_drop( struct StructInfo *pstruct , FILE *fp_dsc_drop_sql )
{
	int			c ;
	
	fprintf( fp_dsc_drop_sql , "-- It had generated by DirectStruct v%s\n" , DIRECTSTRUCT_VERSION );
	
	for( c = 0 ; c < pstruct->drop_sql_count ; c++ )
	{
		fprintf( fp_dsc_drop_sql , "\n" );
		fprintf( fp_dsc_drop_sql , "%s\n" , pstruct->drop_sql[c] );
	}
	
	fprintf( fp_dsc_drop_sql , "\n" );
	fprintf( fp_dsc_drop_sql , "DROP TABLE %s ;\n" , pstruct->struct_name );
	fprintf( fp_dsc_drop_sql , "\n" );
	
	return 0;
}

int GenerateSqlCode( struct CommandParameter *pcp , struct StructInfo *pstruct , FILE *fp_dsc_create_sql , FILE *fp_dsc_drop_sql )
{
	int		nret = 0 ;
	
	/* Generate *.dsc.create.sql */
	nret = GenerateSqlCode_sql_create( pstruct->next_struct , fp_dsc_create_sql ) ;
	if( nret )
		return nret;
	
	/* Generate *.dsc.drop.sql */
	nret = GenerateSqlCode_sql_drop( pstruct->next_struct , fp_dsc_drop_sql ) ;
	if( nret )
		return nret;
	
	return 0;
}

